apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentName }}
    spec:
      containers:
        - name: {{ .Values.deploymentName }}-container
          image: {{ .Values.imageFullPath | quote }}
          imagePullPolicy: IfNotPresent
          env:
            - name: DEPLOYMENT_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DEPLOYMENT_NAME
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
