apiVersion: apps/v1
kind: Deployment
metadata:
  name: california-housing-explain-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: california-housing-explain-ai
  template:
    metadata:
      labels:
        app: california-housing-explain-ai
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 7860