apiVersion: v1
kind: Service
metadata:
  name: california-housing-explain-ai
spec:
  type: {{ .Values.service.type }}
  selector:
    app: california-housing-explain-ai
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}