name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
      - master

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: ${{ secrets.REGION }}
  REPO_NAME: ${{ secrets.REPO_NAME }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
  DEPLOYMENT_NAME: ${{ secrets.DEPLOYMENT_NAME }}
  NAMESPACE: ${{ secrets.NAMESPACE }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud CLI and kubectl
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: kubectl

      - name: Show active authenticated account
        run: |
          echo "Currently authenticated as:"
          gcloud auth list --filter=status:ACTIVE --format="value(account)"

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker "${{ env.REGION }}-docker.pkg.dev"

      - name: Build Docker image
        id: build-image
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          GIT_SHA=$(git rev-parse --short HEAD)
          TAG="${TIMESTAMP}-${GIT_SHA}"
          IMAGE_URI="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${TAG}"
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

          docker build -t "$IMAGE_URI" .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_URI }}

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --region ${{ env.REGION }} --project ${{ env.PROJECT_ID }}

      - name: Deploy with Helm
        run: |
          helm upgrade --install ${{ env.DEPLOYMENT_NAME }} ./helm_chart \
            --namespace ${{ env.NAMESPACE }} \
            --create-namespace \
            --set image.repository="${{ env.IMAGE_URI%:* }}" \
            --set image.tag="${{ env.IMAGE_URI##*: }}"
