name: Build and Deploy to GKE

on:
  push:
    branches: [ master ]

env:
  INFRA_SECRETS_PROJECT: ${{ secrets.INFRA_SECRETS_PROJECT }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '>= 464.0.0'

      - name: Decode service account key
        run: |
          echo "${{ secrets.GCLOUD_KEY_JSON_B64 }}" | base64 -d > helm_chart/key-file.json

      - name: Authenticate with GCP
        run: |
          gcloud auth activate-service-account --key-file=helm_chart/key-file.json
          gcloud config set project "$INFRA_SECRETS_PROJECT"

      - name: Configure Docker for Artifact Registry
        run: |
          REGION=$(gcloud secrets versions access latest --secret="REGION" --project="$INFRA_SECRETS_PROJECT")
          gcloud auth configure-docker "$REGION-docker.pkg.dev"

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=$(gcloud secrets versions access latest --secret="IMAGE_NAME" --project="$INFRA_SECRETS_PROJECT")
          REPO_NAME=$(gcloud secrets versions access latest --secret="REPO_NAME" --project="$INFRA_SECRETS_PROJECT")
          REGION=$(gcloud secrets versions access latest --secret="REGION" --project="$INFRA_SECRETS_PROJECT")
          PROJECT_ID="$INFRA_SECRETS_PROJECT"

          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          GIT_SHA=$(git rev-parse --short HEAD)
          TAG="${TIMESTAMP}-${GIT_SHA}"

          FULL_IMAGE="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:${TAG}"

          echo "🔨 Building image: $FULL_IMAGE"
          docker build -t "$FULL_IMAGE" .

          echo "📦 Pushing image: $FULL_IMAGE"
          docker push "$FULL_IMAGE"

          echo "IMAGE_TAG=$FULL_IMAGE" >> $GITHUB_ENV

      - name: Get GKE credentials
        run: |
          CLUSTER_NAME=$(gcloud secrets versions access latest --secret="CLUSTER_NAME" --project="$INFRA_SECRETS_PROJECT")
          REGION=$(gcloud secrets versions access latest --secret="REGION" --project="$INFRA_SECRETS_PROJECT")
          PROJECT_ID="$INFRA_SECRETS_PROJECT"

          gcloud container clusters get-credentials "$CLUSTER_NAME" \
            --region "$REGION" \
            --project "$PROJECT_ID"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Deploy using Helm
        run: |
          DEPLOYMENT_NAME=$(gcloud secrets versions access latest --secret="DEPLOYMENT_NAME" --project="$INFRA_SECRETS_PROJECT")
          NAMESPACE=$(gcloud secrets versions access latest --secret="NAMESPACE" --project="$INFRA_SECRETS_PROJECT")

          helm upgrade --install "$DEPLOYMENT_NAME" ./helm_chart \
            --namespace "$NAMESPACE" \
            --create-namespace \
            --set image.repository="${{ env.IMAGE_TAG%:* }}" \
            --set image.tag="${{ env.IMAGE_TAG##*: }}"
