# .github/workflows/test-and-deploy.yml
name: Test and Deploy

on:
  push:
    branches:
      - '**'  
  pull_request: 
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # or whatever version you're using

      - name: Install Pixi
        run: |
          curl -sSL https://pixi.sh/install.sh | bash -s -- --yes
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Run tests in dev environment
        run: pixi run -e dev test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Step
        run: echo "✅ All tests passed. Deploying..."  # replace with real deploy

