name: Test and Deploy on Push to Master

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Pixi
        run: |
          curl -sSL https://pixi.sh/install.sh | bash -s -- --yes
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Run tests in dev environment
        run: pixi run -e dev test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Step
        run: echo "✅ All tests passed. Deploying..."  # Replace with your actual deploy logic
